CREATE TABLE IF NOT EXISTS runs (
 id text PRIMARY KEY, customer_id text NOT NULL, business_date date NOT NULL,
 fixture_revision text NOT NULL DEFAULT 'store-v1', scenario text NOT NULL DEFAULT 'healthy',
 scenario_expires_at timestamptz, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS customers (run_id text REFERENCES runs(id) ON DELETE CASCADE, id text, name text NOT NULL, email text NOT NULL, PRIMARY KEY(run_id,id));
CREATE TABLE IF NOT EXISTS orders (run_id text, id text, customer_id text NOT NULL, sku text NOT NULL, product_name text NOT NULL, purchased_at date NOT NULL, delivered_at date NOT NULL, damaged boolean NOT NULL DEFAULT true, price_minor integer NOT NULL, currency text NOT NULL DEFAULT 'EUR', category text NOT NULL, PRIMARY KEY(run_id,id), FOREIGN KEY(run_id,customer_id) REFERENCES customers(run_id,id));
CREATE TABLE IF NOT EXISTS stock (run_id text REFERENCES runs(id) ON DELETE CASCADE, sku text, available integer NOT NULL CHECK(available>=0), PRIMARY KEY(run_id,sku));
CREATE TABLE IF NOT EXISTS documents (run_id text REFERENCES runs(id) ON DELETE CASCADE, id text, trust text NOT NULL, revision text NOT NULL, body text NOT NULL, PRIMARY KEY(run_id,id));
CREATE TABLE IF NOT EXISTS conversations (run_id text REFERENCES runs(id) ON DELETE CASCADE,id text,customer_id text NOT NULL,order_id text NOT NULL,agent_version text NOT NULL DEFAULT 'baseline',state jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(run_id,id),FOREIGN KEY(run_id,order_id) REFERENCES orders(run_id,id));
CREATE TABLE IF NOT EXISTS proposals (run_id text REFERENCES runs(id) ON DELETE CASCADE,id text,conversation_id text NOT NULL,customer_id text NOT NULL,order_id text NOT NULL,sku text NOT NULL,arrival_date date NOT NULL,requested_by date,raw_carrier jsonb NOT NULL,confirmed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(run_id,id),UNIQUE(run_id,conversation_id,order_id),FOREIGN KEY(run_id,order_id) REFERENCES orders(run_id,id));
CREATE TABLE IF NOT EXISTS confirmations (run_id text,idempotency_key text,proposal_id text NOT NULL,customer_id text NOT NULL,confirmed_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(run_id,idempotency_key),UNIQUE(run_id,proposal_id),FOREIGN KEY(run_id,proposal_id) REFERENCES proposals(run_id,id));
CREATE TABLE IF NOT EXISTS replacements (run_id text,id text,proposal_id text NOT NULL,customer_id text NOT NULL,order_id text NOT NULL,idempotency_key text NOT NULL,arrival_date date NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(run_id,id),UNIQUE(run_id,proposal_id),UNIQUE(run_id,order_id),UNIQUE(run_id,idempotency_key),FOREIGN KEY(run_id,proposal_id) REFERENCES proposals(run_id,id));
CREATE TABLE IF NOT EXISTS notification_deliveries (run_id text,id text,replacement_id text NOT NULL,customer_id text NOT NULL,recipient text NOT NULL,idempotency_key text NOT NULL,body text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(run_id,id),UNIQUE(run_id,replacement_id),UNIQUE(run_id,idempotency_key),FOREIGN KEY(run_id,replacement_id) REFERENCES replacements(run_id,id));
CREATE TABLE IF NOT EXISTS action_attempts (id bigserial PRIMARY KEY,run_id text NOT NULL,conversation_id text,call_id text,tool_name text NOT NULL,status text NOT NULL,reason text,trace_id text,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS carrier_quotes (id bigserial PRIMARY KEY,run_id text NOT NULL,order_id text NOT NULL,raw_response jsonb NOT NULL,mapped_arrival date NOT NULL,trace_id text,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sessions (id text PRIMARY KEY,run_id text REFERENCES runs(id) ON DELETE CASCADE,customer_id text NOT NULL,expires_at timestamptz NOT NULL);
